#ifndef GUTTURAL_CONF_H
#define GUTTURAL_CONF_H


#define GUTTURAL_MAX_STACK_SIZE 256
#define GUTTURAL_MAX_NUM_GLOBALS (1<<5)

#define GUTTURAL_MAX_FUNCTION_CALLS 10000
#define GUTTURAL_MAX_CFUNCTION_CALLS 200


#endif
